### ISSUE TITLE
Nullpointer if bundles were deleted

### ISSUE THREAD

**Issue by roscadbe** [code-distillery/baselining-maven-plugin#9]
If a bundle got deleted completely the baseline plugin fails with a NullPointerException.

Unexpected exception during mojo execution
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unexpected exception during mojo execution
    at net.distilledcode.maven.baselining.BaselineMojo.execute(BaselineMojo.java:180)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
    ... 19 more
Caused by: java.lang.NullPointerException
    at aQute.bnd.version.Version.compareTo(Version.java:83)
    at net.distilledcode.maven.baselining.BaselineMojo.reportFindings(BaselineMojo.java:199)
    at net.distilledcode.maven.baselining.BaselineMojo.execute(BaselineMojo.java:175)
    ... 21 more

The Info element with the Set returned by baseline.getPackageInfos() contains a null value in suggestedVersion.

**Comment by roscadbe** [comment]
Added fix:
https://github.com/roscadbe/baselining-maven-plugin

**Comment by code-distillery** [comment]
Sorry, I don't understand your scenario. Which bundle got deleted completely? Could you please explain exactly what you are doing and why it is not working?

Or even better, supply an automated test case.

Thank you.

**Comment by code-distillery** [comment]
No more feedback. Closing.
